### ISSUE TITLE
[Linux] Segmentation fault on closing the application

### ISSUE THREAD

**Issue by codeling** [3dct/open_iA#13]
When closing the application on Linux, a segmentation fault occurs.
Cause is unknown, gdb shows it to happen in a QWidget destructor triggered from (an automatically created part of) the destructor of the MainWindow:
```
(gdb) where
#0  0x00007ffff64e921a in QObjectPrivate::~QObjectPrivate() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#1  0x00007ffff6dbef19 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#2  0x00007ffff64f1b48 in QObject::~QObject() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007ffff6dc12c9 in QHBoxLayout::~QHBoxLayout() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007ffff6dcbb3f in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007ffff6dcbbf5 in QGridLayout::~QGridLayout() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007ffff6dcbc19 in QGridLayout::~QGridLayout() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ffff6dec549 in QWidget::~QWidget() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007ffff6fa77c9 in QDialog::~QDialog() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007ffff64e828b in QObjectPrivate::deleteChildren() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007ffff6dec708 in QWidget::~QWidget() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007ffff79671f7 in MainWindow::~MainWindow() () from /workspace/open_iA/bin/bin/libopen_iA_Core.so
#12 0x0000000000401631 in main ()
```
(happens in Ubuntu 16.04 LTS, with its default Qt 5.5).

**Comment by codeling** [comment]
Workaround fix: not unloading modules before shutting down program.
